title:
email: steph@stephanemourey.fr
description: >
  Desc
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
theme: taorain
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


timezone: Europe/Paris
permalink: /:title.html
