title: Couacs
email: steph@stephanemourey.fr
description: >
  Faux haïkus et tweets pour amateurs de littérature miniature
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://couacs.stephanemourey.fr" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
theme: taorain
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


timezone: Europe/Paris
permalink: /:title.html
